spring:
  datasource:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password:
hibernate:
  hbm2ddl:
    auto: create-drop
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
